manifest:
  remotes:
    - name: TonyWu20
      url-base: https://github.com/TonyWu20
  projects:
    - name: zmk
      remote: TonyWu20
      revision: feat/pointers-move-scroll-smooth
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: TonyWu20
      revision: smooth-scroll
  self:
    path: config
